// =============================================================================
// SharedResultPage — Public Share Result Viewer
// =============================================================================
//
// Route: /shared/:token — outside ProtectedRoute and AppShell.
//
// This page is intentionally auth-free.  It must NOT import AuthContext,
// apiFetch, or any component that assumes an active session.  The page is
// accessed by patients using a share link generated by their doctor.
//
// Data flow:
//   - Calls getSharedResult(token) — a plain fetch, no auth cookie.
//   - Image URLs are built from the public endpoint pattern:
//       /api/shared/:token/files/:imageResultId/original
//       /api/shared/:token/files/:imageResultId/mask
//
// Error handling:
//   - 410 Gone → expired link message
//   - 404 Not Found → invalid link message
//   - Other errors → generic error message
//
// Image overlay:
//   - Reuses the same OverlayCanvas compositing logic as the authenticated
//     result page so the mask highlight color stays consistent.
//   - The grayscale mask is recolored into the same red highlight used in the
//     doctor-facing result view, which reads more clearly against X-ray tones.
//   - Bounding boxes are drawn on the same canvas when the bbox toggle is on.
//
// ZIP download:
//   - Reuses exportReadyResultsZip from src/lib/resultExport.ts.
//   - exportCanvas callbacks fetch the original image from the public
//     endpoint and return the blob, so no canvas compositing is needed.

import { getSharedResult } from "@/api/shareLinks";
import type { SharedImageResult, SharedResultResponse } from "@/api/shareLinks";
import { OverlayCanvas } from "@/components/OverlayCanvas";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { exportReadyResultsZip } from "@/lib/resultExport";
import { useQuery } from "@tanstack/react-query";
import { Download, X, ZoomIn } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const APP_NAME = "CariesSeg";
const SHARED_OVERLAY_OPACITY = 60;

// ---------------------------------------------------------------------------
// URL helpers — public endpoints, no auth cookie required
// ---------------------------------------------------------------------------

function publicOriginalUrl(token: string, imageResultId: string): string {
  return `/api/shared/${token}/files/${imageResultId}/original`;
}

function publicMaskUrl(token: string, imageResultId: string): string {
  return `/api/shared/${token}/files/${imageResultId}/mask`;
}

// ---------------------------------------------------------------------------
// SharedImageCard sub-component
// ---------------------------------------------------------------------------

interface SharedImageCardProps {
  token: string;
  result: SharedImageResult;
  /** Whether the mask overlay is enabled globally. */
  showOverlay: boolean;
  /** Whether bounding boxes are enabled globally. */
  showBoundingBoxes: boolean;
  onZoom: (result: SharedImageResult) => void;
}

/**
 * Render one image result card on the shared result page.
 *
 * Stacks the original image, an optional mask overlay, and an optional
 * bounding-box canvas layer using CSS position:absolute.  The container's
 * aspect ratio is derived from the original image dimensions so the layout
 * remains stable even before images load.
 */
function SharedImageCard({
  token,
  result,
  showOverlay,
  showBoundingBoxes,
  onZoom,
}: SharedImageCardProps) {
  const { t } = useTranslation();

  const originalUrl = publicOriginalUrl(token, result.id);
  const maskUrl = publicMaskUrl(token, result.id);

  const { width, height } = result.original_size;
  const paddingBottom = `${((height / width) * 100).toFixed(2)}%`;

  // ---------------------------------------------------------------------------
  // Per-image download — fetch the original as a blob, trigger download
  // ---------------------------------------------------------------------------

  const handleDownload = useCallback(async () => {
    try {
      const res = await fetch(originalUrl);
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      // Preserve the original filename for the download.
      anchor.download = result.original_filename;
      anchor.click();
      URL.revokeObjectURL(url);
    } catch {
      // Silently ignore download failures on the patient-facing page.
    }
  }, [originalUrl, result.original_filename]);

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <Card>
      <CardContent className="p-4 space-y-3">
        <div className="flex items-center justify-between">
          <p className="text-sm font-medium truncate">{result.original_filename}</p>
          <Button variant="ghost" size="sm" onClick={handleDownload}>
            <Download className="h-4 w-4 mr-1.5" />
            {t("shared.download.image")}
          </Button>
        </div>

        {result.is_ready ? (
          /* ---------------------------------------------------------------- */
          /* Image display area — same colored overlay treatment as ResultPage */
          /* ---------------------------------------------------------------- */
          <div
            className="cursor-zoom-in"
            onClick={() => onZoom(result)}
            role="button"
            tabIndex={0}
            aria-label={t("shared.download.image")}
            onKeyDown={(e) => { if (e.key === "Enter") onZoom(result); }}
          >
            <div className="relative">
              <OverlayCanvas
                originalUrl={originalUrl}
                maskUrl={maskUrl}
                opacity={showOverlay ? SHARED_OVERLAY_OPACITY : 0}
                boundingBoxes={result.bounding_boxes}
                showBoundingBoxes={showBoundingBoxes}
                originalSize={result.original_size}
              />

              {/* Zoom hint icon */}
              <div className="absolute top-2 right-2 bg-black/50 rounded p-1 pointer-events-none">
                <ZoomIn className="h-4 w-4 text-white" />
              </div>
            </div>
          </div>
        ) : (
          /* ----------------------------------------------------------------
           * Processing placeholder
           * --------------------------------------------------------------- */
          <div
            className="w-full flex items-center justify-center rounded-md bg-muted"
            style={{ paddingBottom }}
          >
            <p className="absolute text-muted-foreground text-sm">
              {t("shared.processing")}
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Fullscreen zoom modal
// ---------------------------------------------------------------------------

interface ZoomModalProps {
  result: SharedImageResult | null;
  token: string;
  showOverlay: boolean;
  onClose: () => void;
}

/**
 * Simple fullscreen overlay for tapping into a single image.
 * Click or press Escape to close.
 */
function ZoomModal({ result, token, showOverlay, onClose }: ZoomModalProps) {
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", handleKey);
    return () => document.removeEventListener("keydown", handleKey);
  }, [onClose]);

  if (!result) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/90"
      onClick={onClose}
      role="dialog"
      aria-modal
    >
      <Button
        variant="ghost"
        size="sm"
        className="absolute top-4 right-4 text-white hover:text-white hover:bg-white/20"
        onClick={onClose}
        aria-label="Close"
      >
        <X className="h-5 w-5" />
      </Button>
      <div
        className="w-[min(95vw,1200px)]"
        onClick={(e) => e.stopPropagation()}
      >
        <OverlayCanvas
          originalUrl={publicOriginalUrl(token, result.id)}
          maskUrl={publicMaskUrl(token, result.id)}
          opacity={showOverlay ? SHARED_OVERLAY_OPACITY : 0}
          originalSize={result.original_size}
          showBoundingBoxes={false}
          className="max-h-[90vh] border-white/10 bg-black"
        />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Error cards
// ---------------------------------------------------------------------------

function ErrorCard({ title, description }: { title: string; description: string }) {
  return (
    <div className="min-h-screen flex items-center justify-center p-6 bg-background">
      <Card className="max-w-sm w-full text-center">
        <CardContent className="pt-8 pb-8 space-y-2">
          <p className="text-lg font-semibold">{title}</p>
          <p className="text-sm text-muted-foreground">{description}</p>
        </CardContent>
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------

/**
 * Public shared result page at /shared/:token.
 *
 * Completely auth-free — rendered outside ProtectedRoute and AppShell.
 * Fetches scan data via the public GET /api/shared/:token endpoint and
 * presents it in a mobile-first layout suitable for patients.
 */
export default function SharedResultPage() {
  const { token } = useParams<{ token: string }>();
  const { t } = useTranslation();

  const [showOverlay, setShowOverlay] = useState(true);
  const [showBoundingBoxes, setShowBoundingBoxes] = useState(false);
  const [zoomedResult, setZoomedResult] = useState<SharedImageResult | null>(null);
  const [isDownloadingAll, setIsDownloadingAll] = useState(false);

  // ---------------------------------------------------------------------------
  // Data fetching — plain fetch via getSharedResult (no auth cookie)
  // ---------------------------------------------------------------------------

  const {
    data,
    error,
    isLoading,
  } = useQuery<SharedResultResponse, Error>({
    queryKey: ["shared", token],
    queryFn: () => getSharedResult(token!),
    enabled: Boolean(token),
    // Share links are immutable from the patient's perspective once fetched.
    // A long stale time avoids redundant re-fetches while the patient browses.
    staleTime: 5 * 60_000,
    retry: false,
  });

  // ---------------------------------------------------------------------------
  // Download all — reuse exportReadyResultsZip with public URL callbacks
  // ---------------------------------------------------------------------------

  const handleDownloadAll = useCallback(async () => {
    if (!data || !token) return;

    const readyResults = data.image_results.filter((r) => r.is_ready);
    if (readyResults.length === 0) return;

    const items = readyResults.map((r) => ({
      imageResultId: r.id,
      originalFilename: r.original_filename,
      // Fetch the original image from the public endpoint as a blob.
      exportCanvas: async () => {
        const res = await fetch(publicOriginalUrl(token, r.id));
        return res.blob();
      },
    }));

    setIsDownloadingAll(true);
    try {
      await exportReadyResultsZip(token.slice(0, 8), items);
    } catch {
      // Silently ignore — patients cannot action a ZIP error meaningfully.
    } finally {
      setIsDownloadingAll(false);
    }
  }, [data, token]);

  // ---------------------------------------------------------------------------
  // Error states
  // ---------------------------------------------------------------------------

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="flex flex-col items-center gap-4">
          <div className="h-10 w-10 animate-spin rounded-full border-4 border-primary border-t-transparent" />
          <p className="text-muted-foreground text-sm">{t("shared.loading")}</p>
        </div>
      </div>
    );
  }

  if (error) {
    // Determine error type from HTTP status code.
    // ApiError carries the status; a generic Error is treated as unknown.
    const status = (error as { status?: number }).status;

    if (status === 410) {
      return (
        <ErrorCard
          title={t("shared.error.expired.title")}
          description={t("shared.error.expired.desc")}
        />
      );
    }

    return (
      <ErrorCard
        title={t("shared.error.invalid.title")}
        description={t("shared.error.invalid.desc")}
      />
    );
  }

  if (!data) return null;

  // ---------------------------------------------------------------------------
  // Success render
  // ---------------------------------------------------------------------------

  const readyCount = data.image_results.filter((r) => r.is_ready).length;
  const hasBoundingBoxes = data.image_results.some(
    (r) => r.bounding_boxes && r.bounding_boxes.length > 0,
  );

  const formattedScanDate = new Date(data.scan_date).toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="min-h-screen bg-background">
      {/* -------------------------------------------------------------------- */}
      {/* Header bar — clinic branding                                          */}
      {/* -------------------------------------------------------------------- */}
      <header className="sticky top-0 z-10 border-b bg-background/95 backdrop-blur">
        <div className="max-w-2xl mx-auto px-4 py-3 flex items-center justify-between">
          <span className="font-semibold text-sm tracking-tight">{APP_NAME}</span>
          {readyCount > 0 && (
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownloadAll}
              disabled={isDownloadingAll}
            >
              <Download className="h-4 w-4 mr-1.5" />
              {t("shared.download.all")}
            </Button>
          )}
        </div>
      </header>

      {/* -------------------------------------------------------------------- */}
      {/* Page body                                                             */}
      {/* -------------------------------------------------------------------- */}
      <main className="max-w-2xl mx-auto px-4 py-6 space-y-6">
        {/* Page heading */}
        <div>
          <h1 className="text-2xl font-bold tracking-tight">
            {data.patient_name
              ? t("shared.header.resultsFor", { name: data.patient_name })
              : t("shared.header.dentalResults")}
          </h1>
          <p className="text-sm text-muted-foreground mt-1">{formattedScanDate}</p>
        </div>

        {/* Global overlay controls */}
        {readyCount > 0 && (
          <div className="flex flex-wrap gap-4">
            <div className="flex items-center gap-2">
              <Switch
                id="show-overlay"
                checked={showOverlay}
                onCheckedChange={setShowOverlay}
              />
              <Label htmlFor="show-overlay" className="text-sm">
                {t("shared.overlay.showOverlay")}
              </Label>
            </div>

            {hasBoundingBoxes && (
              <div className="flex items-center gap-2">
                <Switch
                  id="show-bboxes"
                  checked={showBoundingBoxes}
                  onCheckedChange={setShowBoundingBoxes}
                />
                <Label htmlFor="show-bboxes" className="text-sm">
                  {t("shared.overlay.showBboxes")}
                </Label>
              </div>
            )}
          </div>
        )}

        {/* Image cards */}
        <div className="space-y-4">
          {data.image_results.map((result) => (
            <SharedImageCard
              key={result.id}
              token={token!}
              result={result}
              showOverlay={showOverlay}
              showBoundingBoxes={showBoundingBoxes}
              onZoom={setZoomedResult}
            />
          ))}
        </div>

        {/* Footer */}
        <footer className="border-t pt-4 text-center space-y-1">
          <p className="text-xs text-muted-foreground">
            {t("shared.footer.poweredBy", { brand: APP_NAME })}
          </p>
          <p className="text-xs text-muted-foreground">
            {data.expires_at
              ? t("shared.footer.expiresAt", {
                  date: new Date(data.expires_at).toLocaleDateString(undefined, {
                    year: "numeric",
                    month: "short",
                    day: "numeric",
                  }),
                })
              : t("shared.footer.noExpiry")}
          </p>
        </footer>
      </main>

      {/* -------------------------------------------------------------------- */}
      {/* Fullscreen zoom overlay                                               */}
      {/* -------------------------------------------------------------------- */}
      <ZoomModal
        result={zoomedResult}
        token={token!}
        showOverlay={showOverlay}
        onClose={() => setZoomedResult(null)}
      />
    </div>
  );
}
